backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/merch"
public_folder: "/assets/images/merch"

- name: "merch"
    label: "Товары"
    folder: "_data" # CMS будет искать файлы тут
    filter: {field: "slug", value: ""} # Фильтр, если нужно
    extension: "yml"
    create: true # Вот эта кнопка Add
    fields:
      - {label: "ID (slug)", name: "slug", widget: "string"}
      - {label: "Название", name: "title", widget: "string"}
      - {label: "Цена", name: "price", widget: "string"}
      - {label: "Картинка", name: "image", widget: "image"}