backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/merch"
public_folder: "/assets/images/merch"

collections:
  - name: "merch_data"
    label: "Магазин"
    files:
      - label: "Список товаров"
        name: "items"
        file: "_data/merch.yml" # Указываем конкретный файл
        fields:
          - label: "Товары"
            name: "merch" # Это должно совпадать с заголовком в твоем merch.yml
            widget: "list"
            fields:
              - {label: "ID (slug)", name: "slug", widget: "string"}
              - {label: "Название", name: "title", widget: "string"}
              - {label: "Цена", name: "price", widget: "string"}
              - {label: "Картинка", name: "image", widget: "image"}