backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/merch"
public_folder: "/assets/images/merch"

collections:
  - name: "merch_collection"
    label: "Управление товарами"
    files:
      - label: "Список товаров"
        name: "merch_list"
        file: "_data/merch.yml" # Точный путь к файлу
        fields:
          - label: "Товары"
            name: "merch"
            widget: "list"
            fields:
              - {label: "ID (slug)", name: "slug", widget: "string"}
              - {label: "Название", name: "title", widget: "string"}
              - {label: "Цена", name: "price", widget: "string"}
              - {label: "Картинка", name: "image", widget: "image"}